#include "minishell.h"

int global_signal = 0;

//ut manages SIGINT generated by Ctrl+C

void    sigint_manager(int status)
{
    if (status == SIGINT)
    {
        global_signal = 1;
        write(STDERR_FILENO, "\n", 1);
        rl_redisplay();        
    }
}

//it manages SIGINT with help of a global variable & inputs/outputs

void    manage_multiline(int status)
{
    if (status == SIGINT)
    {
        global_signal = 1;
        ioctl(STDIN_FILENO, TIOCSTI, "\n");
        // rl_replace_line("", 0);
        rl_on_new_line();
    }
}

//it starts signal functions with the mode from the data structure

void    start_signals(t_data *pntr)
{
    if (pntr->mode == MULTILINE)
    {
        signal(SIGINT, &manage_multiline);
        signal(SIGQUIT, SIG_IGN);
    }
    else if (pntr->mode == CHILD)
    {
        signal(SIGINT, SIG_DFL);
        signal(SIGQUIT, SIG_DFL);
    }
    else if (pntr->mode == NON_INTERACT)
    {
        signal(SIGINT, SIG_IGN);
        signal(SIGQUIT, SIG_IGN);
    }
    else if (pntr->mode == INTERACT)
    {
        signal(SIGINT, &sigint_manager);
        signal(SIGQUIT, SIG_IGN);
    }
}

//it sets a mode on a data structure & starts signals

void    set_mode(t_data *pntr, t_set_mode mode)
{
    pntr->mode = mode;
    start_signals(pntr);
}